### ISSUE TITLE
physical range check fails when variable's data are all missing

### ISSUE THREAD

**Issue by dschristianson** [AMF-FLX/AMF-BASE-QAQC#106]
Physical range check fails while plotting when a variable's data are all missing.

There should be a default axis min / max. This error is strange -- seems like we should already be handling this. The variable is FETCH_FILTER.

**Additional context**
This happened on production. Run 78535.
python 3.7.16, matplotlib 2.2.2

Stacktrace:
```
path/AMF-BASE-QAQC/processing/physical_range.py:318: RuntimeWarning: All-NaN axis encountered
  y_max = np.nanmax(y_data)
Path/AMF-BASE-QAQC/processing/physical_range.py:319: RuntimeWarning: All-NaN axis encountered
  y_min = np.nanmin(y_data)
2024-07-02 04:28:47,799 [INFO] BASE Generation - Unhandled exception Axis limits cannot be NaN or Inf
2024-07-02 04:28:47,825 [INFO] BASE Generation - Traceback (most recent call last):
  File "main.py", line 217, in main
    ftp_plot_dir=ftp_plot_dir).driver(d)
  File "path/AMF-BASE-QAQC/processing/physical_range.py", line 252, in driver
    total_count=total_count)
  File "path/AMF-BASE-QAQC/processing/physical_range.py", line 414, in get_status
    plot_paths = self.plot(var_obj, year)
  File "path/AMF-BASE-QAQC/processing/physical_range.py", line 365, in plot
    self.make_plot(time_data, annual_data, var_obj, year, thresholds=False)
  File "path/AMF-BASE-QAQC/processing/physical_range.py", line 327, in make_plot
    plt.ylim((y_min, y_max))
  File "path/py3_7_16/lib/python3.7/site-packages/matplotlib/pyplot.py", line 1598, in ylim
    ret = ax.set_ylim(*args, **kwargs)
  File "path/py3_7_16/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3429, in set_ylim
    bottom = self._validate_converted_limits(bottom, self.convert_yunits)
  File "path/py3_7_16/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 3040, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
```

**Comment by dschristianson** [comment]
The actual issue is that the FETCH_FILTER variable value is FALSE. This is converted into nan by the data_reader and thus not caught in format qaqc.
